require:
  - rubocop-rails
  - rubocop-rspec

Metrics/MethodLength:
  Description: 'Avoid methods longer than 20 lines of code.'
  Max: 20

RSpec/ExampleLength:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude: 
    - spec/**/*.rb

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never
